
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox MainHBox;
	
	private global::Gtk.ScrolledWindow CodeEditorScrolledWindow;
	
	private global::Gtk.TextView CodeEditor;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.WidthRequest = 640;
		this.HeightRequest = 480;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Keyboard Code");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainHBox = new global::Gtk.HBox ();
		this.MainHBox.Name = "MainHBox";
		this.MainHBox.Spacing = 6;
		// Container child MainHBox.Gtk.Box+BoxChild
		this.CodeEditorScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.CodeEditorScrolledWindow.Name = "CodeEditorScrolledWindow";
		this.CodeEditorScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child CodeEditorScrolledWindow.Gtk.Container+ContainerChild
		this.CodeEditor = new global::Gtk.TextView ();
		this.CodeEditor.CanFocus = true;
		this.CodeEditor.Name = "CodeEditor";
		this.CodeEditorScrolledWindow.Add (this.CodeEditor);
		this.MainHBox.Add (this.CodeEditorScrolledWindow);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.MainHBox [this.CodeEditorScrolledWindow]));
		w2.Position = 0;
		this.Add (this.MainHBox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 640;
		this.DefaultHeight = 480;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
